Portifolio e Investment
fontflows/CryptoManagementSystem-POO pull request #13
Opened 2024-10-02 22:45 UTC by davigdomingues

Definição das classes, aplicação de getters e setters, cálculo do portifólio e leitura de arquivo em PortifólioRepository

2024-10-03 14:16 UTC, CN-2104 requested changes

2024-10-03 14:17 UTC, alvarocampioni requested changes

2024-10-03 14:17 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/InvestmentService.java
> +public class InvestmentService {
Por que tem uma classe dentro de outra classe? Como funciona isso?

2024-10-03 14:17 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/InvestmentService.java
> +public class InvestmentService {
Entao é como se o PortfolioServices fosse uma extensao do CryptoService ? Ele nao deveria ter suas funcoes proprias? Nao era pra usar "extends" ?

2024-10-03 15:43 UTC, alvarocampioni requested changes

2024-10-03 15:43 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Investiment.java
> +        public Investiment(double tempo){
Por que o construtor de Investment só aceita o parametro tempo? e os outros campos

2024-10-03 15:43 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/PortifolioService.java
> +public class PortifolioService {
Similarmente, tem uma classe dentro de outra classe.

2024-10-08 15:20 UTC, alvarocampioni requested changes

2024-10-08 15:20 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
>      private String id, userId, list;
Onde essas variaveis sao declaradas?

2024-10-08 15:20 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Investment.java
> +        public Investment(double tempoInvestment){
Construtor so aceita tempo?

2024-10-08 15:20 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Investment.java
> +            (Math.pow(1 + cryptoCurrency, tempo))*tempo), parece calcular o valor presente de uma série de pagamentos
"parece" calcular ?

2024-10-11 11:51 UTC, alvarocampioni requested changes

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    private List<String> list; // Lista de ativos no formato "nome,quantidade"
deveria utilizar uma List de Investments

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    }
utilizar a List de Investments

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    }
utilizar a List de Investments. Percorrer a lista inteira considerando que podem haver mais de um Investment com a mesma moeda.

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    }
percorrer a List de Invesments e vendo se o nome passado no argumento se encontra na Lista

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
>      }
Retornar List de Investments

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    }
metodo getAssets() e getList() sao redundantes

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +        return 31 * id.hashCode() + userId.hashCode();
Onde seria utilizado isso?

2024-10-11 11:51 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +        return sb.toString();
precisa de um "\n" separando os assets. Como sera utilizado a List de Investments vai ser append do  nome da criptomoeda, quantidade e preco. Quantidade pode ser obtida com o metodo getAssetAmount();

2024-10-11 11:51 UTC, CN-2104 requested changes

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Investment.java
Seguir a documentação. Nome em inglês

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Portfolio.java
Seguir a documentação. Nome em inglês

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortifolioRepository.java
Seguir a documentação. Nome em inglês

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Investment.java
> +        public Investment(double cryptoCurrency, double precoCompra, int quantidadeCryptosInvestidos){
Um investment é contido por uma crypytocurrency e não um double.

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Investment.java
> +        public double modulacaoEPrestacaoParcelada(double tempoInvestment){
Se for uma tentativa de calcular o preço do portifolio, não faz sentido

2024-10-11 11:51 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortifolioRepository.java
> +            System.err.println("Erro: Portfólio deve conter pelo menos um ativo.");
Pelo que entendi ".trim" retira os whitespaces de uma string, mas se já é vazio, não terá white spaces
Qual o motivo da rendundância?

2024-10-11 12:23 UTC, CN-2104 requested changes

2024-10-11 12:23 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +        if (assetName == null || assetName.trim().isEmpty()) {
Pelo que entendi ".trim" retira os whitespaces de uma string, mas se já é vazio, não terá white spaces
Porque a redundância?

2024-10-11 12:23 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +        return 31 * id.hashCode() + userId.hashCode();
Se um hashcode chama 31 * hashcode do if (que chama o hash code novamente...) isso não seria um loop infinito?
Realmente não entendi essa parte

2024-10-11 12:23 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortifolioRepository.java
> +            writer.write("\n");
O portifolio.toString já imprime o ID, por que duplicar?
por que os 2 "\n"

2024-10-11 12:23 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortifolioRepository.java
>      }
Não faz sentido realizar a busca no arquivo para cada usuário, faria sentido realizar o carregamento geral na memória, e se necessário, realizar a busca na memória

2024-10-11 12:27 UTC, fontflows submitted a review, later dismissed

2024-10-11 12:27 UTC, fontflows commented on src/main/java/com/cryptomanager/models/Portfolio.java
Os métodos não devem estar no models, o models é somente para implementar a classe,
![1_neBcAZJyLGpE7KHc3sH8bw](https://github.com/user-attachments/assets/9196f67d-5155-49f6-b140-2bf44f07fb9f)
Ou seja, a lógica de negócios, que é o que você está fazendo aqui com as funções, deve estar no diretório de ** services**

2024-10-11 12:27 UTC, fontflows commented on src/main/java/com/cryptomanager/models/Investment.java
Mesmo comentário que fiz na de Portfolio

2024-10-11 12:27 UTC, fontflows commented on src/main/java/com/cryptomanager/CryptoManagementApplication.java
> +        SpringApplication.run(PortifolioRepository.class, args);
Isso não é necessário, não vamos fazer isso para todas as classes, o CryptoManagementApplication vai conter tudo da aplicação. 
Idealmente não é pra mexer nesse arquivo.

2024-10-11 12:27 UTC, fontflows commented on src/main/java/com/cryptomanager/services/PortifolioService.java
Como eu disse antes, aqui que deve estar a lógica de negócios.

2024-10-14 16:13 UTC, alvarocampioni requested changes

2024-10-14 16:13 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/Portfolio.java
>      }
Esse metodo nao cobre todas as possibilidades considerando o metodo que foi utilizado para adicionar Investments;

ex: 
List<Investment> investments = {bitcoin, dogecoin}
addAsset(bitcoin, 10.00, 1)
Nova lista: List<Investment> investments = {bitcoin, dogecoin, bitcoin}

Ao percorrer a lista de Investment e encontrar a primeira ocorrencia da moeda procurada, a funcao ja retorna, ignorando ocorrencias posteriores. Esse metodo pode funcionar se alterar o metodo de addAsset, de modo que ao invez de criar um novo investimento, apenas atualizar o investimento anterior e utilizar o preco medio.

2024-10-14 16:13 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/PortfolioService.java
> +    }
Nao entendi essa relacao de PortfolioService herdar CryptoService.

2024-10-16 22:41 UTC, CN-2104 requested changes

2024-10-16 22:41 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +            System.err.println("Erro: Portfólio inválido.");
Substituir para uma exeção?

2024-10-16 22:41 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +                            .orElse(new Portfolio(portfolioId, userIdFromFile));
Explicar o funcionamento ou colocar outra forma entendível

2024-10-16 22:41 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +                    .orElse(null);
Explicar o funcionamento ou colocar outra forma entendível

2024-10-16 22:45 UTC, davigdomingues commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +                .orElse(null);
Coloquei outra forma, mais entendível. Retirei a estrutura lambda

2024-10-16 22:47 UTC, davigdomingues commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +import java.io.*;
Boa ideia

2024-10-17 01:22 UTC, alvarocampioni requested changes

2024-10-17 01:22 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +            }
Esse loop fica fora do loop de cima, nao faz sentido a cada investimento que for ser analisado procurar o mesmo portfolio repetidamente

2024-10-17 15:42 UTC, alvarocampioni submitted a review, later dismissed

2024-10-17 15:42 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
> +    public List<Portfolio> loadPortfolioByUserId(String userId) {
Considerando que cada user possui apenas um portfolio, este metodo poderia retornar apenas o portfolio ao inves de uma lista

2024-10-20 00:13 UTC, alvarocampioni approved these changes
Ok

2024-10-20 15:24 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    private  List<Investment> investments; // Lista de investimentos
Espaço duplo por algum motivo entre private e List

2024-10-20 16:13 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
![Imagem do WhatsApp de 2024-10-20 à(s) 12 45 00_5b75c376](https://github.com/user-attachments/assets/2bc22bef-3d6c-4fa5-960e-c2b70b8252d9)
![Imagem do WhatsApp de 2024-10-20 à(s) 12 51 19_c080148c](https://github.com/user-attachments/assets/49d98d5a-9d0e-4620-acf3-924c809bea63)
![Imagem do WhatsApp de 2024-10-20 à(s) 12 45 00_9b8bf338](https://github.com/user-attachments/assets/234da9d0-4759-4f39-a066-89855010bf6a)
O salvamento segue o formato:
idport, iduser 
idport, iduser, cryptoname, cryptoqnt, purchaseprice
...
Mas a leitura só lê quando args>=5, logo a parte de 2 argumentos não está redundante?
Se sim, não seria melhor tira-la ou melhor:
idport, iduser 
cryptoname, cryptoqnt, purchaseprice
...
Seguir um formato assim?
if (line.split == 2) idport, id user = xxxx
if (line.split = 3) (ou >2?)
 cryptoname, == x
cryptoqnt,  == x
purchaseprice == x.

Além disso, não há um loop visível (pelo menos não achei) para quando há mais de 1 investment no portifolio, dessa forma acredito que vai dar erro quando tiver investment>1

2024-10-20 23:17 UTC, davigdomingues commented on src/main/java/com/cryptomanager/repositories/CryptoRepository.java
> +        } // ta errado
É uma sinalização que o Fontenele fez para indicar a mudança que ele planeja fazer depois na classe CryptoRepository.

2024-10-22 00:01 UTC, fontflows commented on src/main/java/com/cryptomanager/repositories/PortfolioRepository.java
Resolvi aqui nesse último commit, dá uma olhada

2024-10-22 00:01 UTC, fontflows commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    public void setInvestments(final List<Investment> investments) {this.investments = investments;}
Resolvi aqui nesse último commit, dá uma olhada

2024-10-22 00:01 UTC, fontflows commented on src/main/java/com/cryptomanager/models/Portfolio.java
> +    private  List<Investment> investments; // Lista de investimentos
Resolvi aqui nesse último commit, dá uma olhada

2024-10-22 17:26 UTC, CN-2104 approved these changes

2024-10-23 15:22 UTC, merged