Criei classe InvestmentProjection
fontflows/CryptoManagementSystem-POO pull request #14
Opened 2024-10-03 16:30 UTC by alvarocampioni

Implementa metodo estatico para calcular o valor futuro de um investimento baseado na taxa de crescimento, alem de adicionar método estatico para calcular o tempo necessário para atingir um valor alvo

2024-10-11 12:04 UTC, davigdomingues commented on src/main/java/com/cryptomanager/services/InvestmentProjection.java
> +        if(targetValue < totalValue && growthRate > 0) { return 0; }
o ideal não deveria ser (targetValue < totalValue || growthRate < 0)?
se a condição original for mantida pode ocorrer do crescimento ser negativo e o cálculo mesmo assim ser executado.

2024-10-11 12:10 UTC, fontflows requested changes
Coloca a nomenclatura no Padrão, então seria "InvestmentProjectionService", que aí sempre associa da forma:
InvestmentProjection (em models) > InvestmentProjectionRepository (em repositories) > InvestmentProjectionController (controller) que vamos criar depois para complementar.

2024-10-12 16:32 UTC, davigdomingues approved these changes

2024-10-16 23:27 UTC, CN-2104 approved these changes

2024-10-17 21:36 UTC, davigdomingues commented on src/main/java/com/cryptomanager/services/InvestmentProjectionService.java
> +    public static double calculateInvestmentProjection (int coinAmount, double price, double growthRate, int months){
A variável coinAmount não deveria ser double? Há como exemplo o satoshi dos bitcoins , que equivale a 10^(-8) bitcoins (exemplo que encontrei para ilustrar o ponto).

2024-10-17 21:36 UTC, davigdomingues commented on src/main/java/com/cryptomanager/services/InvestmentProjectionService.java
> +        if (price < 0) { throw new IllegalArgumentException("Preco nao pode ser negativo"); }
O coin amount e o price não poderiam ser iguais a zero, porque ninguém realizaria um investimento com nenhum valor corrente inicial nulo, nem moeda alguma pode valer nada (se não nem faria sentido ela estar na bolsa de valores). A verificação total dos casos está apenas na função calculateTimeToTarget

2024-10-18 12:06 UTC, CN-2104 approved these changes

2024-10-18 12:59 UTC, fontflows approved these changes
boa

2024-10-18 13:00 UTC, merged