implementar-funcionalidade-conversão-criptomoeda
fontflows/CryptoManagementSystem-POO pull request #22
Opened 2024-10-29 02:06 UTC by davigdomingues

Aplicação da conversão entre criptomoedas

2024-10-30 11:49 UTC, CN-2104 requested changes

2024-10-30 11:49 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/CurrencyConverter.java
O usuário/método n deveria poder converter apenas alguma determinada quantidade de cripto, e não todo o "saldo"?

2024-10-30 11:49 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/CurrencyConverter.java
> +        return quantityOriginalCryptoQuantityInvested*toCrypto.getMarketCap()*taxConversionGrowthRate*taxConversionPrice;
Não entendi o uso de marketcap e taxconversionGrowthRate

2024-10-30 11:53 UTC, davigdomingues commented on src/main/java/com/cryptomanager/models/CurrencyConverter.java
Justo. Vou adaptar o retorno

2024-10-31 23:31 UTC, alvarocampioni approved these changes

2024-11-01 00:39 UTC, CN-2104 requested changes

2024-11-01 00:39 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/CurrencyConverter.java
> +        if (balance == 0)
<= 0 , para incluir algum valor negativo 
ai na exceção colocar "tem que ser positivo"
Ou tratar caso balance <0

2024-11-01 00:39 UTC, CN-2104 commented on src/main/java/com/cryptomanager/models/CurrencyConverter.java
> +            if (crypto.getName().equalsIgnoreCase(cryptoName))
Ignorecase? mas nao tem nada relacionado com isso na cryptocurrency

2024-11-01 13:25 UTC, CN-2104 approved these changes

2024-11-01 22:53 UTC, merged