More JavaDoc
fontflows/CryptoManagementSystem-POO pull request #77
Opened 2024-12-03 21:07 UTC by davigdomingues

Documentação em padrão javadoc das classes: InvestmentStrategy, ClientRepository, CryptoRepository, ReportRepository, CryptoService e CurrencyConverterService

2024-12-03 21:59 UTC, alvarocampioni requested changes

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/InvestmentStrategy.java
> +     * @param name Recebe o nome do investimento.
"nome da estrategia de investimento"

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/models/InvestmentStrategy.java
> +     * @param riskQuota Recebe a cota de risco do investimento.
"cota de risco da estrategia de investimento"

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/ClientRepository.java
> +     */
faltou o throws NoSuchElement

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/CryptoRepository.java
> +     * @throws IOException Excecao lacada, caso ocorra algum erro na entrada/saida durante o carregamento das criptomoedas existentes no sistema.
"lancada" escrito errado nesta linha

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
> +    /** Metodo responsavel por obter a soma dos valores armazenados nos relatorios produzidos, durante o uso do sistema.
na real "Sum" vem de summary, é o sumario dos reports ja gerados no sistema. Reformula a documentacao desse metodo.

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
> +    /** Metodo responsavel por gerar a lista de relatorios do sistema.
ele gera um report a partir de uma lista

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/CryptoService.java
> +     */
Faltou documentar o getDeletedCryptosHistory

basicamente retorna o historico das criptomoedas que foram removidas com a motivacao da remocao, faz ai pq ja esta no pull request aberto

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/CurrencyConverterService.java
> +     * @param portfolioRepository Instancia da classe PortfolioRepository, a qual lida com a pertinencid de dados do portfolio no sistema txt.
"pertinencia" escrito errado nessa linha

2024-12-03 21:59 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/CurrencyConverterService.java
> +     * @param cryptoRepository Instancia da classe CryptoRepository, a qual lida com a pertinencid de dados do portfolio no sistema txt.
"pertinencia" escrito errado nessa linha

2024-12-03 22:09 UTC, davigdomingues commented on src/main/java/com/cryptomanager/repositories/CryptoRepository.java
> +     * @throws IOException Excecao lacada, caso ocorra algum erro na entrada/saida durante o carregamento das criptomoedas existentes no sistema.
lacada é sacanagem mesmo kkkkkkkk

2024-12-03 22:16 UTC, davigdomingues commented on src/main/java/com/cryptomanager/services/CurrencyConverterService.java
> +     * @param portfolioRepository Instancia da classe PortfolioRepository, a qual lida com a pertinencid de dados do portfolio no sistema txt.
parece que o id ficou na cabeça, agora temos o pertinencid kkkkkkk

2024-12-03 22:19 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
> +    /** Metodo responsavel por gerar o relatorio do portfolio corrente no sistema.
corrente? 
Acredito que **atual** encaixa melhor

2024-12-03 22:21 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
> +     * @param report Insancia que recebe o relatorio gerado durante o uso do sistema, pelo usuario.
instancia*

2024-12-03 22:32 UTC, alvarocampioni requested changes

2024-12-03 22:32 UTC, alvarocampioni commented on src/main/java/com/cryptomanager/services/CryptoService.java
> +     * @throws NoSuchElementException Excecao lancada, caso o elemento detectado nao exista para o sistema.
Na realidade ele so lanca o CryptoServiceException e nao o NoSuchElement, que é capturado no catch e relancado como CryptoServiceException

2024-12-03 22:36 UTC, davigdomingues commented on src/main/java/com/cryptomanager/services/CryptoService.java
> +     * @throws NoSuchElementException Excecao lancada, caso o elemento detectado nao exista para o sistema.
Desatentei-me com o detalhe

2024-12-03 22:37 UTC, alvarocampioni approved these changes

2024-12-04 00:12 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
>       * @return Retorna o indice associado a lista gerada.
ao relatório* gerado da lista

2024-12-04 00:16 UTC, CN-2104 approved these changes

2024-12-04 00:17 UTC, CN-2104 commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
>       * @return Retorna o indice associado a lista gerada.
no Return especificamente

2024-12-04 02:13 UTC, davigdomingues commented on src/main/java/com/cryptomanager/repositories/ReportRepository.java
>       * @return Retorna o indice associado a lista gerada.
Caramba, acabei não percebendo que confundi na descrição... o pior é que o parâmetro foi especificado corretamente em seguida kkkkkkkk

2024-12-04 02:13 UTC, merged